#!/bin/bash

# Deployment script for Render.com with Firebase Admin SDK
# This script helps you deploy the updated backend with market trading API

echo "🚀 Blobis Exchange - Deployment Guide"
echo "======================================"
echo ""

echo "📋 Pre-deployment Checklist:"
echo ""
echo "1. ✅ Backend API endpoints created (market_service.py, backend.py)"
echo "2. ✅ Frontend hooks updated (useMarket.js, useBalance.js)"
echo "3. ✅ Firebase Admin SDK added to requirements.txt"
echo "4. ⚠️  Firebase credentials need to be added to Render"
echo ""

echo "🔥 Firebase Setup Steps:"
echo ""
echo "Step 1: Get Firebase Service Account Key"
echo "  - Go to: https://console.firebase.google.com/"
echo "  - Select project: blobis"
echo "  - Settings → Service Accounts"
echo "  - Click 'Generate New Private Key'"
echo "  - Save as firebase-credentials.json"
echo ""

echo "Step 2: Add to Render.com"
echo "  Option A - Secret File (Recommended):"
echo "    1. Go to: https://dashboard.render.com/web/srv-d7rg9qugvqtc73bfq5i0"
echo "    2. Navigate to 'Environment' tab"
echo "    3. Click 'Add Secret File'"
echo "    4. Filename: firebase-credentials.json"
echo "    5. Contents: Paste your Firebase credentials JSON"
echo ""
echo "  Option B - Environment Variable:"
echo "    1. Convert JSON to base64:"
echo "       cat firebase-credentials.json | base64 > firebase-creds.base64"
echo "    2. Add env var: FIREBASE_CREDENTIALS_BASE64"
echo "    3. Value: Contents of firebase-creds.base64"
echo ""

echo "Step 3: Update Firestore Security Rules"
echo "  - Go to: https://console.firebase.google.com/project/blobis/firestore/rules"
echo "  - Copy rules from MARKET_API.md"
echo "  - Publish rules"
echo ""

echo "Step 4: Deploy to Render"
echo "  1. Commit changes:"
echo "     git add ."
echo "     git commit -m 'Add market trading API with global pool'"
echo "     git push origin main"
echo ""
echo "  2. Render will auto-deploy, or trigger manual deploy:"
echo "     - Go to Render Dashboard"
echo "     - Click 'Manual Deploy' → 'Clear build cache & deploy'"
echo ""

echo "✅ Post-deployment Verification:"
echo ""
echo "Test endpoints:"
echo "  curl https://blobis-gqla.onrender.com/api/market/pool"
echo "  curl https://blobis-gqla.onrender.com/api/market/stats"
echo ""

echo "📊 What's New:"
echo "  ✅ Global liquidity pool (all players trade together)"
echo "  ✅ Backend validation (no localStorage manipulation)"
echo "  ✅ Firebase Transactions (atomic operations)"
echo "  ✅ Rate limiting (10 trades/min per user)"
echo "  ✅ Trade hashing (SHA256 validation)"
echo "  ✅ 24h statistics"
echo "  ✅ Real-time updates via Firebase"
echo ""

echo "🔒 Security Improvements:"
echo "  ✅ No localStorage for critical data"
echo "  ✅ All trades validated on backend"
echo "  ✅ Firebase Security Rules prevent client writes"
echo "  ✅ Slippage protection"
echo "  ✅ Balance checks before trades"
echo ""

echo "📝 Next Steps (Phase 2):"
echo "  - Market maker bots for liquidity"
echo "  - Candle aggregation system"
echo "  - Multiple timeframes (1m, 5m, 15m, 1h, 4h, 1d)"
echo "  - Technical indicators (MA/EMA)"
echo ""

echo "🎯 Ready to deploy? Follow the steps above!"
